on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g. 2021.11.13-1)'
        required: true

name: Release

jobs:
  build:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          npm version ${{ github.event.inputs.version }}
          npm ci
          npm run pack
          npm run dist
          git push origin v${{ github.event.inputs.version }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            dist/*.exe
